# name: VPC module build, test and deploy pipeline.
# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     name: Terraform
#     steps:
#       - name: Build the Docker image
#         uses: actions/checkout@v3

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.1.9
#           terraform_wrapper: false

#       - name: Terraform Init
#         id: init
#         run: terraform init
#         # env:
#         #   ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }} # This doesn't have to be a secret. Client IDs are not sensitive.
#         #   ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         #   ARM_SUBSCRIPTION_ID: "[Your Subscription ID]"
#         #   ARM_TENANT_ID: "[Your Tenant ID]"
#         # working-directory: ./staging # Use your environment folder
#         shell: bash

name: VPC module build, test and deploy pipeline.
on: [push]
permissions:
  contents: read
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Infracost installation and authentification
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost --version
          infracost configure set api_key ico-VydNjDztDoYtENuV8MYHiy5De0EYb9zG

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan
