name: VPC module build, test and deploy pipeline.
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: staging
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
