name: VPC module build, test and deploy pipeline.
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform
    environment: staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Terraform init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
        run: terraform init
        shell: bash
