name: VPC module build, test and deploy pipeline.
on: [push]
permissions:
  contents: read
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run module test
        uses: actions/checkout@v3

  post_build:
    runs-on: ubuntu-latest
    steps:
      - name: Infracost installation and authentification
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          infracost --version
          infracost configure set api_key ${{ secrets.INFRACOST_API_KEY }}
          infracost breakdown --path .
